[package]
name = "hash-visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.24.5"
fnv = "1.0.7"
bitvec = "1.0.1"
argh = "0.1.10"




